### ISSUE TITLE
Add os_name alias mechanism

### ISSUE THREAD

**Issue by jeremyschulman** [jeremyschulman/netcfgbu#19]
In order to avoid copy/paste of os_name section content, provide a means to alias one on_name to another.  For example alias "catos" to be the same as "ios":

```toml
[os_name.ios]
    aliases = ['catos']
    pre_get_config = "terminal length 0"
```
